version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_prisma
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nestjs_prisma
    ports:
      - "3050:3000"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  # frontend:
  #   build:
  #     context: ./frontend
  #     depends_on:
  #       postgres:
  #         condition: service_health
  #     ports:
  #       - "5000:5000"

volumes:
  postgres_data:
